name       : kmime
version    : 17.04.1
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/kmime-17.04.1.tar.xz : 28fbc7844b41884d1c0cbf6e2f5600136bdcbca352c55186f5d3c218639c9a2e
license    : LGPL-2.1
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles.
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
