name       : kmime
version    : 17.12.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/kmime-17.12.1.tar.xz : 1d2031eb0feed93bc8e590144119b43e9121ef9e70616b949bd6d5ee48cca998
license    : LGPL-2.1
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles.
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
