name       : kmime
version    : 20.12.2
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/kmime-20.12.2.tar.xz : f18520bd2c4106edf996ea01ab6060071f4c5359ca83a61840515ec19486eeca
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
