name       : kmime
version    : 20.04.1
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.1/src/kmime-20.04.1.tar.xz : 59d0ec6905c7a7228f7837c2e498052e84484954e1ea42b1c720f81cb2eb6db6
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
