name       : kmime
version    : 22.04.1
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/kmime-22.04.1.tar.xz : a7f94a60d204f7546a711551feafb05549caf25d5831ecb9942cad32caddca05
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
