name       : kmime
version    : 18.04.2
release    : 11
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/kmime-18.04.2.tar.xz : b0f4ce9eec34be71c6f18ae4213ea76fad006a4f928a1cb6e3e457e2d85d020a
license    : LGPL-2.1
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
