name       : kmime
version    : 20.04.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.0/src/kmime-20.04.0.tar.xz : 4230ca0147d31fa688cf84ac8e7bb46e64deb9536b7a25544be73171615c8fac
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
