name       : kmime
version    : 18.04.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/kmime-18.04.0.tar.xz : 1d67589bda24661f6e7e397ed75c1274018939aa7cc13350332784351bdf1c0e
license    : LGPL-2.1
component  : desktop.library
optimize   : lto
summary    : KMime is a library for handling mail messages and newsgroup articles.
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
