name       : kmime
version    : 19.12.1
release    : 30
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/kmime-19.12.1.tar.xz : 4d6db5d59b239b884bf8811f3ea616520ab1f69224a809cef3f79023b2563085
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
