name       : kmime
version    : 18.08.1
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/kmime-18.08.1.tar.xz : dd14d7813199f4f859cb112dc34113269196c62fd9f05359e889913eb9d55d02
license    : LGPL-2.1
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
