name       : kmime
version    : 21.08.3
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/kmime-21.08.3.tar.xz : 66cfc3fcdffe779ff89fa54955b8d4c2a56caaafe31656508ffe3b48b5b6afae
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
