name       : kmime
version    : 21.04.1
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/kmime-21.04.1.tar.xz : d368a8270833910d0fadf84424a547abee46263ec2bf8dbc245d6fc7222546f8
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
