name       : kmime
version    : 18.12.1
release    : 18
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.1/src/kmime-18.12.1.tar.xz : c20219f978f328dd5246775a5135386ce43d465fef2fb503f4d4cda614767216
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
