name       : kmime
version    : 17.08.2
release    : 4
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/kmime-17.08.2.tar.xz : 6af1916c73278b9255ce28205fe2f94de0f22d1979d785b1062e0343f56723aa
license    : LGPL-2.1
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles.
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
