name       : kmime
version    : 20.08.1
release    : 38
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/kmime-20.08.1.tar.xz : cd0beaa46040d571b505d07853be76f099289e22d99ce4884695d4d645dfbe8c
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
