name       : kmime
version    : 18.08.2
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.2/src/kmime-18.08.2.tar.xz : 2796457f5b5818c5e26edf47623438a9b49384603a50d63377de1cfb6ed3a8eb
license    : LGPL-2.1
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
