name       : kmime
version    : 17.04.0
release    : 1
source     :
    - https://download.kde.org/stable/applications/17.04.0/src/kmime-17.04.0.tar.xz : 1707f2c496d0da01ff5eed5d4df93634f51d1790aebfdb99eeb70bb4adfadcaf
license    : LGPL-2.1
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles.
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
