name       : kmime
version    : 21.04.3
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.3/src/kmime-21.04.3.tar.xz : 42923dc4f755909d49387f43bef79d72e44f1a187c85f95d5195db91a26e8d16
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
