name       : kmime
version    : 17.08.3
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/kmime-17.08.3.tar.xz : 6d8807b9669a0547ff39cf01544f307c12c98fc75b612f7c24da371e1ee2f19f
license    : LGPL-2.1
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles.
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
