name       : kmime
version    : 20.12.3
release    : 45
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/kmime-20.12.3.tar.xz : 381e6839d8f830e5b7b31a6272122676e935cf4b25857ca9b247cc9572ef476d
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
