name       : kmime
version    : 18.12.0
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/kmime-18.12.0.tar.xz : 223bf626e00664bc3ca8688cbd18e68e13ee7ac6f677449e8946b1de85d9014e
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
