name       : kmime
version    : 19.04.3
release    : 24
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.3/src/kmime-19.04.3.tar.xz : a6fe422eddb15eb52fbacde97b45ec6752b60f46149657a3bb7f48dc899e1c02
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : KMime is a library for handling mail messages and newsgroup articles
description: |
    KMime is a library for handling mail messages and newsgroup articles.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
